config/routes.rb
Rails.application.routes.draw do

resources :users        
resources :texts
resources :tags
resources :comments
resources :feedbacks
resources :ratings

root 'static_pages#home'

get 'help'    => 'static_pages#help'
get 'about'   => 'static_pages#about'
get 'tc' => 'static_pages#terms_and_conditions'
get 'contact' => 'static_pages#contact'
get 'signup'  => 'users#new'
get    'login'   => 'sessions#new'
post   'login'   => 'sessions#create'
delete 'logout'  => 'sessions#destroy'
get 'new_text' => 'texts#new'
delete 'remove_text' => 'texts#destroy'
get 'lock_text' => 'texts#lock'
get 'unlock_text' => 'texts#unlock'
get 'search_by_tag' => 'tags#show'
get'list_texts' => 'texts#bytag'
post 'leave_comment' => 'texts#comment'
get 'leave_feedback' => 'feedbacks#new'
get 'bad_show' => 'texts#unsatisfactory_proofreading'
get 'good_show' => 'texts#satisfactory_proofreading'
get 'rate_text' => 'texts#rate'
get 'search' => 'texts#search'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about     
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
The <b>ProofreadIt!</b> platform provides the capability for the creative fiction writers to cooperate and help each other in proofreading their works.
<br/><br/>Version: 1.0
<br/><br/>Developer: Andrey Shevyakov
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
<b>Table of Contents:</b><br/>
<ul class="np help-p">
<li><a href="#concept">Concept</a></li>
<li><a href="#user-profile">User Profile</a></li>
<li><a href="#adding-texts">Submitting Texts</a></li>
<li><a href="#editing-texts">Editing Texts</a></li>
<li><a href="#administering-texts">Administering Texts</a></li>
<li><a href="#search-methods">Search Methods</a></li>
<li><a href="#banning-system">Ban System</a></li>
<li><a href="#contacts">Contacts</a></li>
</ul>
</p>

<span class="helph" id="concept">Concept</span>
<p class="help-p">
The <b>ProofreadIt!</b> platform provides the capability for the creative fiction writers to cooperate and help each other in proofreading their works.
</p>

<span class="helph" id="user-profile">User Profile</span>
<p class="help-p">
From the <b>User Profile</b> page, you can submit new texts, view the previously submitted texts, see how many submissions you have got left, and search for others' texts. In order to access the <b>User Profile</b>
page, click the <b>Account</b> link located at the navigation bar on top of the page and then select the <b>Profile</b> option.
</p>

<span class="helph" id="adding-texts">Submitting Texts</span>
<p class="help-p">
In order to add new text, click the <b>Add Text</b> button located at the <b>User Profile</b> page. You will be redirected shortly to the <b>Add Text</b>
 page. Enter the tags separated by commas into the <b>Tags</b> entry field and enter the text into the <b>Text</b> entry field. Now, click the <b>Submit</b> 
 button. You will be redirected shortly to the editing page for the newly submitted text.
 <br/><br/>
 It is important to remember that you will not be able to add any texts if you are out of submission tokens. You will earn one submission token each time
  your proofreading work was deemed satisfactory by the text's author. 
</p>

<span class="helph" id="editing-texts">Editing Texts</span>
<p class="help-p">
At the <b>Text Correction</b> page you can edit the submitted text if it is unlocked for corrections, rate the text (1 to 5 stars), and leave comments. 
When you are done editing the text, click the <b>Save Changes</b> button.
</p>

<span class="helph" id="administering-texts">Administering Texts</span>
<p class="help-p">
At any time, you can lock any of your submitted texts from further editing by clicking the <b>Lock Editing</b> button at the text's page. 
In the same manner, you can unlock any of your submitted texts by clicking the <b>Allow Editing</b> button at the locked text's page. 
You can also delete any of your submitted texts by clicking the <b>Delete Text</b> button at the text's page.<br/><br/>
It is important that you do not forget to rate the work done by your proofreaders. The rating options (Yes | No) will appear at the text's page if someone has 
edited your text.
</p>

<span class="helph" id="search-methods">Search Methods</span>
<p class="help-p">
There are two ways in which you can search texts: via the search bar or by tag.<br/><br/>
The search bar can be found at the <b>User Profile</b> page.<br/><br/>
In order to list all tags, click the <b>Proofread Text</b> button at the <b>User Profile</b> page. You will be redirected shortly to the <b>Tags</b> page, 
listing all the tags. Click on the tag describing the text you are looking for or would be interested in proofreading. You will be redirected shortly to the 
<b>Texts by Tag</b> page where all texts described by the selected tag will be listed. Select the text you are looking for or would be interested in proofreading. 
You will be shortly redirected to the text editing page. 
</p>

<span class="helph" id="banning-system">Ban System</span>
<p class="help-p">
The website automatic ban system is based on the 3-strike rule. If your proofreading quality is deemed unsatisfactory three times in a row, you are automatically 
banned for a week.
</p>

<span class="helph" id="contacts">Contacts</span>
<p class="help-p">
You can contact me via the <b>Feedback</b> form accessible by clicking the <b>Feedback</b> link located in the footer.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
<h1>Welcome to ProofreadIt!</h1>
<h2>
Welcome to <b>ProofreadIt!</b>. It is a helpful tool for writers that allow them to cooperate and help each other with proofreading their work.
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>      

app/views/static_pages/terms_and_conditions.html.erb
<% provide(:title, 'Terms & Conditions') %>
<h1>Terms &amp; Conditions</h1>
<p>
<b>Introduction</b>
<br/><br/>
These terms and conditions govern your use of this website. By using this website, you accept these terms and conditions in full. 
If you disagree with these terms and conditions or any part of these terms and conditions, you must not use this website. 
You must be at least 13 years of age to use this website.  By using this website and by agreeing to these terms and conditions, 
you warrant and represent that you are at least 13 years of age.
<br/><br/>
This website uses cookies.  By using this website and agreeing to these terms and conditions, you consent to use of cookies.
<br/><br/>

<b>License</b>
<br/><br/>
The code, assets, and functionality provided by the website is the sole property of Andrey Shevyakov. It is restricted to copy or modify the website content in 
any manner. Under any conditions, the texts submitted remain the intellectual property of the submitting party.
<br/><br/>
The website is provided "as is" without any representations or warranties, express or implied.
<br/><br/>

<b>Acceptable Use</b>
<br/><br/>
You must not use this website in any way that causes, or may cause, damage to the website or impairment of the availability or accessibility of the website; or in any way which is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity.
<br/><br/>
You must not use this website to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, Trojan horse, worm, keystroke logger, rootkit or other malicious computer software.
<br/><br/>
You must not conduct any systematic or automated data collection activities (including without limitation scraping, data mining, data extraction and data harvesting) on or in relation to this website without Andrey Shevyakov's express written consent.
<br/><br/>
You must not use this website to transmit or send unsolicited commercial communications.
<br/><br/>

<b>Restricted Access</b>
<br/><br/>
Your user account may be disabled without notice or explanation.
<br/><br/>

<b>Limitations of Liability</b>
<br/><br/>
Andrey Shevyakov is not responsible for any consequences of using the website.
<br/><br/>

<b>Variation</b>
<br/><br/>
These terms and conditions may be revised. Revised terms and conditions will apply to the use of this website from the date of the publication of the revised terms and conditions. Please check this page regularly to ensure you are familiar with the current version.
</br></br>

<b>Ownership</b>
<br/><br/>
The website's ownership may be transferred without notice or explanation.
<br/><br/>

<b>Credit</b>
<br/><br/>
This document was created using a modified Contractology template available at <a href="http://www.freenetlaw.com">http://www.freenetlaw.com</a>.<br/>
This website utilises jQuery highlightTextarea available at <a href="http://mistic100.github.io/jquery-highlighttextarea/">http://mistic100.github.io/jquery-highlighttextarea/</a>, developed by Damien Sorel aka mistic100.

</p>