config/routes.rb
Rails.application.routes.draw do

resources :users        
resources :texts
resources :tags
resources :comments
resources :feedbacks
resources :ratings

root 'static_pages#home'

get 'help'    => 'static_pages#help'
get 'about'   => 'static_pages#about'
get 'tc' => 'static_pages#terms_and_conditions'
get 'contact' => 'static_pages#contact'
get 'signup'  => 'users#new'
get    'login'   => 'sessions#new'
post   'login'   => 'sessions#create'
delete 'logout'  => 'sessions#destroy'
get 'new_text' => 'texts#new'
delete 'remove_text' => 'texts#destroy'
get 'lock_text' => 'texts#lock'
get 'unlock_text' => 'texts#unlock'
get 'search_by_tag' => 'tags#show'
get'list_texts' => 'texts#bytag'
post 'leave_comment' => 'texts#comment'
get 'leave_feedback' => 'feedbacks#new'
get 'bad_show' => 'texts#unsatisfactory_proofreading'
get 'good_show' => 'texts#satisfactory_proofreading'
get 'rate_text' => 'texts#rate'
get 'search' => 'texts#search'

end

app/models/user.rb
class User < ActiveRecord::Base
      attr_accessor :remember_token
      before_save { self.email = email.downcase }
      before_save { self.name = self.name.split.map(&:capitalize).join(' ') }
      validates :name, presence: true, length: { in: 4..70 }
      validates :description, presence: true, length: { in: 10..70 }
      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      validates :email, presence: true, 
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
      validates :password, presence: true, length: { minimum: 6 }
      validates :password_confirmation, presence: true
      validates :dob, presence: true, date: {after: Proc.new {Time.now - 100.years}, message: "must enter a valid date of birth"}
      validates :dob, date: {before: Proc.new {Date.today - 13.years}, message: "have to be at least 13 years old to use the service"}
      has_secure_password      # A magic method!!
      has_many :texts, :foreign_key => 'author'
      has_many :comments, :foreign_key => 'commenter'
      has_many :ratings, :foreign_key => 'user_id'
	  has_many :bugs

      # Returns the hash digest of a string.
      def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end

      # Returns a random token.
      def User.new_token
        SecureRandom.urlsafe_base64
      end

      # Remembers a user in the database for use in persistent sessions.
      def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
      end

      def authenticated?(remember_token)
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
      end

       def forget
          update_attribute(:remember_digest, nil)
       end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

helper_method :restrict_access

def index
	redirect_to root_path
end

def new
	if logged_in? then
		flash[:warning] = "You are already registered" 
		redirect_to current_user
	else
		@user = User.new
	end
end

def show
	restrict_access
	
	if current_user.banned != nil and current_user.banned < Date.today - 7.days
		User.find(current_user.id).update_attribute(:banned, nil)
		flash[:success] = "The Ban Period Is Over!"
		redirect_to current_user
	end
	
	@user = User.find(params[:id])
	
	if current_user.id != @user.id
		redirect_to root_path
	end
	
	@texts = @user.texts

	# Wishing User Happy Birthday
	if @user.dob.today? then 
		flash.now[:notice] = "Happy Birthday, #{@user.name}!"
	end 
end

def create
	secure_params = params.require(:user).permit(:name, :email, :dob, :description, :gender, 
	:password, :password_confirmation)
	@user = User.new(secure_params)
	if @user.save
		remember @user     
		flash.now[:success] = "Welcome to the ProofreadIt!"    
		redirect_to @user
	else
		render 'new' 
	end
end

end

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>   
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :description %>
<%= f.text_field :description %>

<%= f.label "Date of Birth" %>
<%= f.date_field :dob, value: Date.today %>

<div id="input-radio">
<%= f.label "Gender" %><br/>
<%= f.label "Male" %>
<%= f.radio_button :gender, "Male", checked: true %> 
<%= f.label "Female" %>
<%= f.radio_button :gender, "Female", checked: false %> 
</div>

<%= f.label :email %>
<%= f.email_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation %>

<%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
<aside class="col-md-8">
<section class="user_info">
<h1 style="margin-bottom: 15px;"><%= @user.name %></h1>
<% if @user.banned == nil %>
<% if @user.tokens != 0 %>
<%= link_to "Add Text", new_text_path, class: "btn btn-lg btn-primary" %>
<%= link_to "Proofread Text", search_by_tag_path, class: "btn btn-lg btn-primary" %>
<% else %>
<%= link_to "Add Text", new_text_path, class: "btn btn-lg btn-primary", disabled: "disabled" %>
<%= link_to "Proofread Text", search_by_tag_path, class: "btn btn-lg btn-primary blue-highlight" %>
<% end %>
<span id="sub-info">Submission Tokens Left: <%= @user.tokens %> <% if @user.tokens == 0 %>(Proofread Others' Texts To Earn Some Tokens!)<% end %></span>

<%= form_tag(search_path, :method => "get", id: "search-form") do %>
<div class="input-append">
<%= text_field_tag :search, params[:search], id: "search-bar", placeholder: "Search Texts" %>
<button class="btn" type="submit"><i class="glyphicon glyphicon-search"></i></button>
</div>
<% end %>
</aside>
</section>
</div>
<div class="row">
<h1>Submitted Texts</h1>
<ul id="texts-list">
<% @texts.each do |t| %>
<li><%= link_to t.content[0..15] + "...", t, class: "btn btn-primary"%></li>
<% end %>
</ul>
</div>
<% else %>
</aside>
</section>
</div>
<div class="row">
<h2>Due to the unsatisfactory proofreading quality, you are temporarily banned until <%= @user.banned + 7.days %>.</h2>
</div>
<% end %>