config/routes.rb
Rails.application.routes.draw do

resources :users        
resources :texts
resources :tags
resources :comments
resources :feedbacks
resources :ratings

root 'static_pages#home'

get 'help'    => 'static_pages#help'
get 'about'   => 'static_pages#about'
get 'tc' => 'static_pages#terms_and_conditions'
get 'contact' => 'static_pages#contact'
get 'signup'  => 'users#new'
get    'login'   => 'sessions#new'
post   'login'   => 'sessions#create'
delete 'logout'  => 'sessions#destroy'
get 'new_text' => 'texts#new'
delete 'remove_text' => 'texts#destroy'
get 'lock_text' => 'texts#lock'
get 'unlock_text' => 'texts#unlock'
get 'search_by_tag' => 'tags#show'
get'list_texts' => 'texts#bytag'
post 'leave_comment' => 'texts#comment'
get 'leave_feedback' => 'feedbacks#new'
get 'bad_show' => 'texts#unsatisfactory_proofreading'
get 'good_show' => 'texts#satisfactory_proofreading'
get 'rate_text' => 'texts#rate'
get 'search' => 'texts#search'

end

app/models/text.rb
class Text < ActiveRecord::Base
	before_save { self.content = content.strip }
	validates :content, presence: true, :uniqueness => {:message => "was already submitted"}, length: { minimum: 100 }
	validates :corrected_content, length: { minimum: 100 }, :on => :update
	validates :tags, presence: true
	belongs_to :user
	has_many :comments, :foreign_key => 'ctext'
	has_many :ratings, :foreign_key => 'text_id'
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

	helper_method :restrict_access
	helper_method :restrict_access_banned
	before_action :restrict_access
	before_action :restrict_access_banned
	
	def index
		redirect_to root_path
	end

	def new
		@text = Text.new
	end

	def show
		@text = Text.find(params[:id])
		
		begin
			@all_ratings = @text.ratings
			@first = true
			@avg = 0
			@all_ratings.each do |r| 
				@avg = @avg + r.rating
				if @first == true
					@first = false
				else
					@avg = @avg / 2
				end
			end
			rescue
			if @all_ratings == nil
				@avg = 0
			else 
				@avg = @all_ratings.rating
			end
		ensure
		end
		
		@avg = @avg.round

		@comments = @text.comments
	end

	def edit
		@text = Text.find(params[:id])
	end

	def comment
		secure_params = params.require(:comment).permit(:ctext, :commenter, :content)
		@comment = Comment.new(secure_params)
		
		if @comment.save then
			flash[:success] = "Commented" 
		else
			flash[:error] = "Can't Leave Blank Comments"
		end
		
		redirect_to text_path(Text.find(secure_params[:ctext])) + "#comment-header"
	end

	def bytag
		
		@tag = params[:tagname]
		@result = []
		@texts = Text.find_each do |t|
			t.tags.split(",").each do |tt|
				if (tt == @tag) then 
					@result.push t 
				end
			end
		end
	end

	def update
		
		@text = Text.find(params[:id])
		corr_c = @text.corrected_content
		@comments = @text.comments
		secure_params = params.require(:text).permit(:corrected_content, :proofreader)
		secure_params[:proofreader] = current_user.id
		if @text.update_attributes(secure_params)
			flash[:success] = "Text Updated"
			@text.update_attribute(:proofread_rated, false)
			redirect_to @text
		else
			@text.corrected_content = corr_c
			render 'show'
		end
	end

	def create
		
		# Should Delete Last Author - Did
		secure_params = params.require(:text).permit(:author, :tags, :content)
		secure_params[:author] = current_user.id
		
		@user = User.find(secure_params[:author])
		
		if @user.tokens != 0
			tags = secure_params[:tags].split(",")
				
			tags_in = ""
			index = 0
			
			tags.each do |t|
			
				t = t.strip.downcase
				
				if index != 0 
					tags_in = tags_in + "," + t 
				else
					tags_in = t
				end
				
				index+= 1
				
			end
			
			secure_params[:tags] = tags_in

			begin
				tags.each do |t|
					t = t.strip.downcase
					tp = params.permit(:name)
					tp[:name] = t
					tag = Tag.new(tp)
					tag.save
			end

			rescue
			ensure
			end

			secure_params[:corrected_content] = secure_params[:content]
			@text = Text.new(secure_params)
			if @text.save
				@user.update_attribute(:tokens, @user.tokens - 1)
				flash[:success] = "Text Submited"  
				redirect_to @text  
			else
				render 'new'
			end
			
		else
			flash[:error] = "Not Enough Tokens"
			redirect_to current_user
		end
		
	end
	
	def destroy
		
		@text = Text.find(params[:id])
		
		if @text.author == current_user.id 
			Text.find(params[:id]).destroy
			flash[:success] = "Text Deleted"
			redirect_to current_user
		else
			redirect_to root_path
		end
	end
	
	def lock
		@text = Text.find(params[:id])
		
		if @text.author == current_user.id
			Text.find(params[:id]).update_attribute(:locked, true)
			flash[:success] = "Text Locked"
			redirect_to @text
		else
			redirect_to root_path
		end
	end
	
	def unlock
		@text = Text.find(params[:id])
		
		if @text.author == current_user.id
			Text.find(params[:id]).update_attribute(:locked, false)
			flash[:success] = "Text Unlocked"
			redirect_to @text
		else
			redirect_to root_path
		end
	end
	
	def satisfactory_proofreading
		@reader = User.find(params[:reader_id])
		
		if @reader.strikes > 0
			User.find(@reader.id).update_attribute(:strikes, @reader.strikes - 1)
		end
		
		@reader.update_attribute(:tokens, @reader.tokens + 1)
		
		Text.find(params[:text_id]).update_attribute(:proofread_rated, true)
		
		flash[:success] = "Rated"
		redirect_to Text.find(params[:text_id])
	end
	
	def unsatisfactory_proofreading
		@reader = User.find(params[:reader_id])
		
		if @reader.strikes < 3
			@reader.update_attribute(:strikes, @reader.strikes + 1)
		end
		
		if @reader.strikes == 3
			@reader.update_attribute(:banned, Date.today)
		end
		
		Text.find(params[:text_id]).update_attribute(:proofread_rated, true)
		
		flash[:success] = "Rated"
		redirect_to Text.find(params[:text_id])
	end
	
	def rate
		secure_params = params.permit(:user_id, :text_id, :rating)
		@text = secure_params[:text_id]
		secure_params[:user_id] = current_user.id
		
		@rating = nil
		@rating = Rating.find_by_text_id_and_user_id(secure_params[:text_id], secure_params[:user_id])
		
		if @rating != nil
			Rating.find(@rating.id).destroy
		end
		
		@rating = Rating.new(secure_params)
		
		if @rating.save
			flash[:success] = "Rated!"
		else
			flash[:error] = "Something Went Wrong"
		end
		
		render js: "window.location = '#{@text}'"
	end
	
	def search
		@search_term = params[:search].gsub(/[^0-9a-z ]/i, '').downcase.strip.split(" ")
		@results = []
		@all_texts = Text.all
		
		@all_texts.each do |t| 
			@search_term.each do |s_word|
			 
				User.find(t.author).name.split(" ").each do |a_name|
					if a_name.casecmp(s_word).zero?
						@results << t
					end
				end
				
				t.tags.split(",").each do |tag_c|
					if tag_c.casecmp(s_word).zero?
						@results << t
					end
				end
				
				if t.corrected_content.downcase.include? s_word
					@results << t
				end 
				
				if t.content.downcase.include? s_word
					@results << t
				end
				
			end
		end
		
		@results = @results.uniq
	end
	
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/texts/bytag.html.erb
<% provide(:title, "Texts By Tag") %>
<H1 style="word-wrap: break-word;">Tag <%= @tag%></h1>
<ul>
<% @result.each do |r| %>
<li><%= link_to r.content[0..15] + "... by " + User.find(r.author).name, r, class: "btn btn-primary"%></li><br/><br/><br/>
<% end %>
</ul>

app/views/texts/new.html.erb
<% provide(:title, 'Submit New Text') %>
<h1>Add Text</h1>

<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_for @text do |f| %>
<%= render 'shared/error_messages_text' %>   

<div class="tags-entry">
<%= f.label :tags %>
<%= f.text_field :tags %>

<div class="tags-help">
<span>Separate tags with commas.</span>
<br/>
</div>
</div>

<%= f.label :content %>
<%= f.text_area :content, size: "24x6" %>

<%= f.submit("Submit", class: "btn btn-primary")%>
<% end %>
</div>
</div>

app/views/texts/search.html.erb
<% provide(:title, "Text Search") %>
<h1>Search Results</h1>
<%= form_tag(search_path, :method => "get", id: "search-form") do %>
<div class="input-append">
<%= text_field_tag :search, params[:search], id: "search-bar", value: "#{params[:search]}" %>
<button class="btn" type="submit"><i class="glyphicon glyphicon-search"></i></button>
</div>
<% end %>
<% if @results.length != 0 %>
<ul id="texts-list" class="np">
<% @results.each do |t| %>
<li><%= link_to t.corrected_content[0..15] + " by " + User.find(t.author).name, t, class: "btn btn-primary" %></li>
<% end %>
</ul>
<% else %>
<p>Nothing was found.</p>
<% end %>

app/views/texts/show.html.erb
<% provide(:title, "Text Correction") %>
<% @reader = User.find(@text.proofreader).name rescue "No One"%>
<%= javascript_include_tag 'jquery.highlighttextarea.min' %>
<H1>Text Of <%= User.find(@text.author).name%></H1>
<H1>Last Corrected By <%= @reader%></H1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_for(@text) do |f| %>
<span style="display: none" id="text-id-val"><%=@text.id%></span>
<%= render 'shared/error_messages_text' %>
<%= f.label "Text", id:"content"%>

<% if @text.locked == false %>
<%= f.text_area :corrected_content, rows: 10 %>
<% else %>
<%= f.text_area :corrected_content, rows: 10, disabled: "disabled" %>
<% end %>

<textarea id="orig", style="display: none;"><%=@text.content%></textarea>
<textarea id="corr", style="display: none;"><%=@text.corrected_content%></textarea>
<textarea id="curc", style="display:none;"></textarea>

<% if browser.mobile? %>
<% else %>
<div id="text-manipulation">
<a class="btn btn-info" onclick="show_original_text($('#orig').text())" id="show-text">Show Original Text</a>
<a class="btn btn-info" onclick="highlight_differences($('#corr').text(), $('#orig').text())" id="highlight-text" data-state="off">Highlight Corrections Made</a>
<a class="btn btn-info" onclick="undo_current_changes($('#corr').val())" id="undo-text">Undo Current Changes</a>
</div>

<div id="highlight-explanations">
<span style="color:#76EE00;">Line Added</span>
<span style="color:orange;">Line Changed</span>
<span style="color:red;">Line Removed</span>
</div>
<% end %>

<% if current_user.id == @text.author %>
<% if @text.locked == false %>
<%= link_to "Lock Editing", lock_text_path(:id => @text.id), class: "btn btn-primary", id: "lock-btn" %>
<% else %>
<%= link_to "Allow Editing", unlock_text_path(:id => @text.id), class: "btn btn-primary", id: "lock-btn" %>
<% end %>
<%= link_to "Delete Text", remove_text_path(:id => @text.id), class: "btn", id: "delete-btn", method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<span style="display:none;" id="avg-val"><%=@avg%></span>
<span style="display:none;" id="star-selected-path"><%= asset_path 'star_selected.png' %></span>
<span style="display:none;" id="star-selected-glow-path"><%= asset_path 'star_selected_glow.png' %></span>
<span style="display:none;" id="star-unselected-path"><%= asset_path 'star_unselected.png' %></span>
<div style="margin-bottom: 15px, overflow: auto;" id="tags-desc">Tags: 
<% @text.tags.split(",").each do |t| %>
<% if t.length > 10 %>
<%= link_to t[0..10] + "...", list_texts_path(tagname: t), class: "btn btn-primary btn-small" %>
<% else %>
<%= link_to t, list_texts_path(tagname: t), class: "btn btn-primary btn-tags-text" %>
<% end %>
<% end %>
</div>
<div style="margin-bottom: 15px" id="rating-bar">Rating:
<% for i in 1..5 %>
<% if i <= @avg %>
<%= image_tag 'star_selected.png', class: "star rated" %>
<% else %>
<%= image_tag 'star_unselected.png', class: "star unrated" %>
<% end %>
<% end %>
</div>
<%= f.submit "Save Changes", class: "btn btn-primary", id: "text-change-btn", disabled: "disabled"%>
<% end %>
<% if current_user.id == @text.author and @text.proofread_rated == false %>
<% if @reader != "No One" %>
<div style="margin-top: 15px"><span>Are you satisfied with the work done by <%= @reader %>?: <%= link_to "Yes", good_show_path(:reader_id => @text.proofreader, :text_id => @text.id)%> | <%= link_to "No", bad_show_path(:reader_id => @text.proofreader, :text_id => @text.id) %></span></div>
<% end %>
<% end %>

<div id="comment-area">
<div id="comment-header">Comments</div>

<% flash.each do |message_type, message| %> 
<% if message == "Can't Leave Blank Comments" or message == "Commented" %>
<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<% end %>

<% if @comments.length != 0 %>
<ul id="comments-list" class="np">
<% @comments.each do |c| %>
<li>"<%= c.content %>" - <%= User.find(c.commenter).name %>, <%= c.created_at.strftime("%Y-%m-%d")%></li>
<% end %>
</ul>
<% else %>
Be the first to leave a comment!
<% end %>

</div>

<div id="leave-comment">
<% @comment = Comment.new %>
<%= form_for @comment, :url => leave_comment_path do |f| %>
<%= f.label "Comment" %>
<%= f.text_area :content%>
<%= f.hidden_field :ctext, :value => @text.id %>
<%= f.hidden_field :commenter, :value => current_user.id %>

<%= f.submit "Leave comment", class: "btn btn-primary" %>
<%end%>
</div>
</div>
</div>

<%=javascript_include_tag "inline/rating_change_listener"%>
<%=javascript_include_tag "inline/textarea_change_listener"%>