config/routes.rb
Rails.application.routes.draw do

resources :users        
resources :texts
resources :tags
resources :comments
resources :feedbacks
resources :ratings

root 'static_pages#home'

get 'help'    => 'static_pages#help'
get 'about'   => 'static_pages#about'
get 'tc' => 'static_pages#terms_and_conditions'
get 'contact' => 'static_pages#contact'
get 'signup'  => 'users#new'
get    'login'   => 'sessions#new'
post   'login'   => 'sessions#create'
delete 'logout'  => 'sessions#destroy'
get 'new_text' => 'texts#new'
delete 'remove_text' => 'texts#destroy'
get 'lock_text' => 'texts#lock'
get 'unlock_text' => 'texts#unlock'
get 'search_by_tag' => 'tags#show'
get'list_texts' => 'texts#bytag'
post 'leave_comment' => 'texts#comment'
get 'leave_feedback' => 'feedbacks#new'
get 'bad_show' => 'texts#unsatisfactory_proofreading'
get 'good_show' => 'texts#satisfactory_proofreading'
get 'rate_text' => 'texts#rate'
get 'search' => 'texts#search'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
<b><i>ProofreadIt!&copy;</i></b> By Andrey Shevyakov
</small>
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Terms & Conditions", tc_path %></li>
<li><%= link_to "Feedback", leave_feedback_path%></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<%= link_to "ProofreadIt!", root_path, id: "logo" %>
<nav>
<ul class="nav navbar-nav navbar-right">
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Help", help_path %></li>
<% if logged_in? %>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
Account <b class="caret"></b>
</a>
<ul class="dropdown-menu">
<li><%= link_to "Profile", current_user %></li>
<li class="divider"></li>
<li>
<%= link_to "Log out", logout_path, method: "delete" %>
</li>
</ul>
</li>
<% else %>
<li><%= link_to "Log in", login_path %></li>
<% end %>
</ul>
</nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>ProofreadIt! | <%= yield(:title) %></title>
<%= stylesheet_link_tag 'application', media: 'all',
'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<% flash.each do |message_type, message| %>    
<% if message != "Can't Leave Blank Comments" and message != "Commented" %>
<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<% end %>                                      
<%= yield %>
<%= render 'layouts/footer' %>
</div>
</body>
</html>